const { Post } = require('../models')

const postdata = [
  {
    title: 'Important Story',
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Leo vel orci porta non pulvinar neque laoreet. Turpis massa sed elementum tempus egestas sed. Eget duis at tellus at urna condimentum mattis pellentesque id. Mi in nulla posuere sollicitudin. Diam maecenas sed enim ut. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elit at imperdiet dui accumsan sit amet. Leo duis ut diam quam nulla porttitor massa id. Massa id neque aliquam vestibulum. Ut consequat semper viverra nam libero. Amet consectetur adipiscing elit pellentesque habitant morbi. Nascetur ridiculus mus mauris vitae ultricies. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Id semper risus in hendrerit gravida rutrum quisque non tellus. Viverra adipiscing at in tellus. Blandit massa enim nec dui nunc mattis. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Vitae aliquet nec ullamcorper sit amet. Non consectetur a erat nam at lectus urna duis convallis. Sed nisi lacus sed viverra tellus in hac. Est ante in nibh mauris cursus. Ac tortor dignissim convallis aenean et tortor. Tortor id aliquet lectus proin nibh. Tempor id eu nisl nunc mi. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Vel risus commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu. Turpis egestas maecenas pharetra convallis posuere. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Nunc pulvinar sapien et ligula. Lorem mollis aliquam ut porttitor. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Aliquet nec ullamcorper sit amet risus. Egestas purus viverra accumsan in nisl nisi scelerisque. Diam vel quam elementum pulvinar etiam. Lorem dolor sed viverra ipsum. Elementum integer enim neque volutpat ac tincidunt vitae semper. Proin sed libero enim sed faucibus turpis. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Vel facilisis volutpat est velit egestas. Vestibulum rhoncus est pellentesque elit. Lectus proin nibh nisl condimentum id venenatis. Diam sollicitudin tempor id eu nisl nunc mi. Pulvinar mattis nunc sed blandit. Facilisi cras fermentum odio eu feugiat pretium. Quis vel eros donec ac odio tempor orci. Sed libero enim sed faucibus turpis in eu mi bibendum. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Dictum varius duis at consectetur lorem donec massa. Euismod in pellentesque massa placerat. Est pellentesque elit ullamcorper dignissim. Dui id ornare arcu odio ut. Justo nec ultrices dui sapien eget mi. Vel facilisis volutpat est velit egestas. Rhoncus dolor purus non enim praesent elementum.

    Eros donec ac odio tempor orci dapibus ultrices. Id aliquet risus feugiat in ante metus dictum. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Vulputate sapien nec sagittis aliquam. Vitae congue eu consequat ac felis. In fermentum posuere urna nec tincidunt. Arcu vitae elementum curabitur vitae. Accumsan lacus vel facilisis volutpat. Non arcu risus quis varius quam quisque id diam vel. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Arcu odio ut sem nulla pharetra diam. Dolor magna eget est lorem ipsum dolor sit. Adipiscing bibendum est ultricies integer quis.`,
    author_id: 1
  },
  {
    title: 'My Life Story',
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Leo vel orci porta non pulvinar neque laoreet. Turpis massa sed elementum tempus egestas sed. Eget duis at tellus at urna condimentum mattis pellentesque id. Mi in nulla posuere sollicitudin. Diam maecenas sed enim ut. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elit at imperdiet dui accumsan sit amet. Leo duis ut diam quam nulla porttitor massa id. Massa id neque aliquam vestibulum. Ut consequat semper viverra nam libero. Amet consectetur adipiscing elit pellentesque habitant morbi.

    Nascetur ridiculus mus mauris vitae ultricies. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Id semper risus in hendrerit gravida rutrum quisque non tellus. Viverra adipiscing at in tellus. Blandit massa enim nec dui nunc mattis. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Vitae aliquet nec ullamcorper sit amet. Non consectetur a erat nam at lectus urna duis convallis. Sed nisi lacus sed viverra tellus in hac. Est ante in nibh mauris cursus. Ac tortor dignissim convallis aenean et tortor.

    Tortor id aliquet lectus proin nibh. Tempor id eu nisl nunc mi. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Vel risus commodo viverra maecenas accumsan lacus. Ornare quam viverra orci sagittis eu. Turpis egestas maecenas pharetra convallis posuere. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Nunc pulvinar sapien et ligula. Lorem mollis aliquam ut porttitor. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Aliquet nec ullamcorper sit amet risus. Egestas purus viverra accumsan in nisl nisi scelerisque. Diam vel quam elementum pulvinar etiam. Lorem dolor sed viverra ipsum. Elementum integer enim neque volutpat ac tincidunt vitae semper.

    Proin sed libero enim sed faucibus turpis. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Vel facilisis volutpat est velit egestas. Vestibulum rhoncus est pellentesque elit. Lectus proin nibh nisl condimentum id venenatis. Diam sollicitudin tempor id eu nisl nunc mi. Pulvinar mattis nunc sed blandit. Facilisi cras fermentum odio eu feugiat pretium. Quis vel eros donec ac odio tempor orci. Sed libero enim sed faucibus turpis in eu mi bibendum. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Dictum varius duis at consectetur lorem donec massa. Euismod in pellentesque massa placerat. Est pellentesque elit ullamcorper dignissim. Dui id ornare arcu odio ut. Justo nec ultrices dui sapien eget mi. Vel facilisis volutpat est velit egestas. Rhoncus dolor purus non enim praesent elementum.

    Eros donec ac odio tempor orci dapibus ultrices. Id aliquet risus feugiat in ante metus dictum. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Vulputate sapien nec sagittis aliquam. Vitae congue eu consequat ac felis. In fermentum posuere urna nec tincidunt. Arcu vitae elementum curabitur vitae. Accumsan lacus vel facilisis volutpat. Non arcu risus quis varius quam quisque id diam vel. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Arcu odio ut sem nulla pharetra diam. Dolor magna eget est lorem ipsum dolor sit. Adipiscing bibendum est ultricies integer quis.`,
    author_id: 1
  },
]

const seedPost = () => Post.bulkCreate(postdata);

module.exports = seedPost;